spring:
  application:
    name: Notification_Service
  datasource:
    url: jdbc:mysql://localhost:3306/orderflow_microserviceproject
    username: root
    password: Root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: komal7870sharma@gmail.com
    password: cxid thjh ugfz lidy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9094

inventory:
  low:
    threshold: 10

admin:
  email: mrinalbca.coc@email.com

notification:
  orderId: "ORDER_123"




