spring:
  application:
    name: Notification_Service
  datasource:
    url: jdbc:mysql://localhost:3306/orderflow_microserviceproject
    username: root
    password: Root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9094

notification:
  orderId: "ORDER_123"